### ISSUE TITLE
Review Documentation and Tutorial

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-live-diagnostics#7]
https://med-live-diagnostics.readthedocs.io/en/latest/index.html

**Comment by rbeucher** [comment]
Have you had a chance to review this one @svenbuder ?

**Comment by svenbuder** [comment]
Partially. I have reviewed the Overview + Getting Started - they both looked already good and mainly had broken link fixes. I have not given the feedback to Mike, though. Will do that later.
I have also created the content for MLD on the Hive.
Davide is currently reviewing my PR for including MLD in the Hive (should be merged today).
